### ISSUE TITLE
Experiencing Problems

### ISSUE THREAD

**Issue by iremk** [Kickflip/kickflip-ios-sdk#17]
We are experimenting with kickflip. But every time we load the stream, it seems to be starting from the beginning of the stream, so it's not really "live". What are we doing wrong or did we miss the concept of kickflip?
And also we are having problems to start a stream from time to time , maybe lowering the packet size for the uploads will be a solution but even there are docs , we could not figure out what to do.
And one final thing , we read all the issues here and many people asked for that but could not find the solution for : 
"codec not found: h264
[mpegts @ 0x13006be00] muxrate VBR, pcr every 3 pkts, sdt every 200, pat/pmt every 40 pkts"

We are working on an app for iOS , testing on iPhone 6 plus and did the whole pod updates also cleaned xCode Derived data but still the same.

**Comment by TaoistKing** [comment]
"codec not found: h264  is not a problem, you can still record video

**Comment by chrisballinger** [comment]
@iremk Are you still having trouble? You may see a delay when broadcasting but it should appear live when someone joins the stream.
