### ISSUE TITLE
AVAssetWriter appendSampleBuffer failure

### ISSUE THREAD

**Issue by TaoistKing** [Kickflip/kickflip-ios-sdk#19]
hi, i use kickflip to record video, but sometimes when i start a recording, the terminal says: "writer error, the operation couldn't be completed", and i think it is the avassetwriter problem, in VideoEncoder.m file, _writerInput appendSampleBuffer method sometimes fails, and this problem reproduces easily, about ten percent of all recordings. 
the worst thing is , when this situation occurs, i cannot solve this by restarting another recording, the following recording will always failure. i searched the net and couldn't find a answer, plz help, thanks in advance..
the _writer.error message is "Error Domain=AVFoundationErrorDomain Code=-11800, this operation couldn't be completed. OSStatus error -12983, NSLocalizedFailureReason=Unknown Error"

**Comment by 4netinteractive** [comment]
Same error here, it occures randomly, after that you have to restart the app :(

**Comment by chrisballinger** [comment]
We will be replacing that component for iOS 8 with VideoToolbox, which allows us direct access to the hardware encoders instead of using the janky file reading trick.

**Comment by TaoistKing** [comment]
i solved this problem.
there is a trick, avassetwriter cannot have many instances at the same time, if many instances of avassetwriter exists at the same time, like more than ten, then this error will happen.

i solved this by explicitly release avassetwriter instance as soon as i don't need it . (the kickflip sdk don't release the instance, and maybe that's a bug)

you can refer to this thread for more information:
https://devforums.apple.com/thread/268223?tstart=0

**Comment by chrisballinger** [comment]
@TaoistKing Do you think it's related to #7?

**Comment by TaoistKing** [comment]
@chrisballinger Yes, definitely. That is the correct solution.

**Comment by Arlem** [comment]
@chrisballinger was #7 implemented in the sdk? In which commit?
@TaoistKing Can you help me in implementing koby198s solution?

**Comment by Arlem** [comment]
I don't know if my solution is correct, but it seems to work (according also to instruments allocation log):

- I renamed the dealloc method in shutdown
- Added the following code at the end of stopRecording in KFRecorder.m
```
[self.h264Encoder shutdown];
self.h264Encoder  = nil;
```
