### ISSUE TITLE
BFTask error. 

### ISSUE THREAD

**Issue by Tejas-narola** [Kickflip/kickflip-ios-sdk#28]
After installing new version via pods we are getting attached error. Please help us.
![screen shot 2015-07-03 at 12 21 24 pm](https://cloud.githubusercontent.com/assets/5028455/8499195/81348032-21ad-11e5-8702-07a4d7052052.png)

**Comment by luunn54** [comment]
Because lib AWSS3 just has been update from ver 2.1.1 to 2.2.0. Ver 2.2.0 didn't include Bolts lib.
2 option to fix :
- In Kickflip.podspec, change to : s.dependency 'AWSS3', '2.1.1'
- In Kickflip.podspec : add s.dependency 'Bolts' and add import to your file above.

**Comment by Tejas-narola** [comment]
Thanks for your response. That is issue is solved now. Now we are facing attached issue. Would you please check it? 

![screen shot 2015-07-06 at 2 36 55 pm](https://cloud.githubusercontent.com/assets/5028455/8519715/648b479e-23f2-11e5-81ed-cece1dbb3a19.png)
![screen shot 2015-07-06 at 2 37 14 pm](https://cloud.githubusercontent.com/assets/5028455/8519716/64ce45c6-23f2-11e5-8e91-d0e164bf1169.png)

**Comment by luunn54** [comment]
Because the lastest version of YapDatabase is 2.6.4. It not support that method.
Fix :
In Kickflip.podspec, let change to : s.dependency 'YapDatabase', '2.6.2'
Or
Change code for use with version 2.6.4

**Comment by Tejas-narola** [comment]
An idea, when new version of kick will be available?

**Comment by boztalay** [comment]
This should probably be re-opened, I'm still running into this issue.
