### ISSUE TITLE
Error starting stream: A server with the specified hostname could not be found..

### ISSUE THREAD

**Issue by inturbidus** [Kickflip/kickflip-ios-sdk#64]
Major issue trying to stream.  See screenshot attached.
![2016-10-25-photo-00000082](https://cloud.githubusercontent.com/assets/905441/19693534/e8bec912-9aa9-11e6-9576-5467aa6fe8ba.jpeg)

**Comment by inturbidus** [comment]
@chrisballinger @OnlyInAmerica can you take a look at this?

**Comment by Miserlou** [comment]
DNS issue resolved.

**Comment by chrisballinger** [comment]
There was an issue with our DNS provider, it should be fixed now:
https://kickflip.io

**Comment by inturbidus** [comment]
Thank you!
